/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xkit_demo_jni_HelloJNI */

#ifndef _Included_org_xkit_demo_jni_HelloJNI
#define _Included_org_xkit_demo_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif

JavaVM*   m_pJVM;
jclass    m_class;
jobject   m_jni;
jmethodID m_vmSayHello;

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    initNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xkit_demo_jni_HelloJNI_initNative
  (JNIEnv *, jobject);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    finalizeNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xkit_demo_jni_HelloJNI_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xkit_demo_jni_HelloJNI_print__
  (JNIEnv *, jobject);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xkit_demo_jni_HelloJNI_print__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    echo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xkit_demo_jni_HelloJNI_echo
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    draw
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_xkit_demo_jni_HelloJNI_draw
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xkit_demo_jni_HelloJNI_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
