/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xkit_demo_jni_HelloJNI */

#ifndef _Included_org_xkit_demo_jni_HelloJNI
#define _Included_org_xkit_demo_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xkit_demo_jni_HelloJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xkit_demo_jni_HelloJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
